from .IncomeAgent import IncomeAgent
from .RandomAgent import RandomAgent
from .AdversarialAgent import AdversarialAgent
from .MimickingAgent import MimickingAgent
from .PytorchAgent import PytorchAgent
from .KerasAgent import KerasAgent
from .TaxAgent import TaxAgent
from .TrickyAgent import TrickyAgent
from .StrategicAgentV1 import StrategicAgentV1
from .HonestAgent import HonestAgent
from .Agent import Agent
