"""Add Agent table and elos to User and Agents

Revision ID: 66e9f640b0d2
Revises: 924ab5b05d5f
Create Date: 2020-08-01 13:34:10.518053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e9f640b0d2'
down_revision = '924ab5b05d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('elo', sa.Integer(), server_default='1000', nullable=False),
    sa.Column('n_games', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_type_name'), 'agent_type', ['name'], unique=True)
    op.add_column('user', sa.Column('elo', sa.Integer(), server_default='1000', nullable=False))
    op.add_column('user', sa.Column('n_games', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'n_games')
    op.drop_column('user', 'elo')
    op.drop_index(op.f('ix_agent_type_name'), table_name='agent_type')
    op.drop_table('agent_type')
    # ### end Alembic commands ###
